### ISSUE TITLE
Restore (Resume) attempts

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo-Next#51]
<a href="https://github.com/zachberry"><img src="https://avatars2.githubusercontent.com/u/73479?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zachberry](https://github.com/zachberry)**
_Tuesday Nov 07, 2017 at 23:31 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Next/issues/53_

----

With this added,

* If a user leaves a draft while in Assessment and returns to the draft their draft should be restored.
* They should also be locked into the Assessment as if they hadn't left
* Some modal dialog should alert them that they were in the middle of an assessment attempt and that they will continue

**Comment by zachberry** [comment]
I believe we should hold off on this until #461 is implemented

**Comment by zachberry** [comment]
Closing in favor of #529
